### ISSUE TITLE
vscode-al-variable-quickfixes.checkAndUpdateVariableName fucntion doesnt use ignore prefix

### ISSUE THREAD

**Issue by FavMY** [himanshu2599/AL-Quickfix-#1]
The Prefixes are still there after using the function above.
I would think that the created variable doesnt contain the Prefixes anymore.

**Comment by himanshu2599** [comment]
Bug has been fixed in version [1.2.0] on 25.10.2023.
checkAndUpdateVariableName function support ignore prefix. Go to setting -> Check the "Check and update the variable name".
