### ISSUE TITLE
Suggestion: use selection as scope

### ISSUE THREAD

**Issue by JohnReinhold** [himanshu2599/AL-Quickfix-#2]
It would be great if deleting unused variables only happened within the code that is selected, and not the entire file. In my example below, only myvar3 in MySecond() vil be deleted.

![image](https://user-images.githubusercontent.com/9877709/196362238-4f321891-b24e-4a27-a89f-baf926d752af.png)

**Comment by himanshu2599** [comment]
Feature has been added in version 1.3.0. Use "AL Quickfix: Selected Lines" in Command Palette.
-   Support Quickfix feature on selected lines instead of complete file
-   Use `Shift+CMD+J` on macOS or `Ctrl+Shift+J` on Windows and Linux
